INSERT INTO category(code,name,description) VALUES ('CODE_1','NAME_1','DESCRIPTION_1')
INSERT INTO category(code,name,description) VALUES ('CODE_2','NAME_2','DESCRIPTION_2')
INSERT INTO category(code,name,description) VALUES ('CODE_3','NAME_3','DESCRIPTION_3')
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_1', 'PRODUCT_1', 'DESCRIPTION_1', 17.47, 15.51, 1)
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_2', 'PRODUCT_2', 'DESCRIPTION_2', 27.47, 25.52, 2)
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_3', 'PRODUCT_3', 'DESCRIPTION_3', 37.47, 35.53, 2)
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_4', 'PRODUCT_4', 'DESCRIPTION_4', 47.47, 45.54, 2)
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_5', 'PRODUCT_5', 'DESCRIPTION_5', 57.47, 55.55, 1)
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_6', 'PRODUCT_6', 'DESCRIPTION_6', 67.47, 65.56, 2)
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_7', 'PRODUCT_7', 'DESCRIPTION_7', 77.47, 75.57, 2)
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_8', 'PRODUCT_8', 'DESCRIPTION_8', 87.47, 85.58, 2)
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_9', 'PRODUCT_9', 'DESCRIPTION_9', 97.47, 95.59, 2)
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_10', 'PRODUCT_10', 'DESCRIPTION_10', 107.47, 105.50, 1)
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_11', 'PRODUCT_11', 'DESCRIPTION_11', 117.47, 115.10, 1)
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_12', 'PRODUCT_12', 'DESCRIPTION_12', 127.47, 125.20, 1)
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_13', 'PRODUCT_13', 'DESCRIPTION_13', 137.47, 135.52, 1)
insert into product(code, name, description, acquisition_price, actual_price, category_id) values ('CODE_14', 'PRODUCT_14', 'DESCRIPTION_14', 147.47, 145.50, 1)